[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = 'plur'
version = '0.19'
dependencies = [
  "pexpect",
  "mini"
]

[tool.uv.sources]
mini = { git = "https://github.com/pluripotency/mini" }
